name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install Dependencies
        run: |
          npm ci
          npm install -D terser
        
      - name: Create .env.local file
        run: |
          echo "NEXT_TELEMETRY_DISABLED=1" > .env.local
          echo "NEXT_SWC_MINIFY=true" >> .env.local

      - name: Debug Environment
        run: |
          node --version
          npm --version
          npx terser --version || echo "Terser not found"
          ls -la

      - name: Run Test Build
        run: npm run test-build
        
      - name: Optimize Build
        if: success()
        run: node optimize-build.js

      - name: Verify Output Directory
        run: |
          if [ -d "out" ]; then
            echo "Output directory exists and contains:"
            ls -la out
            echo "Total size:"
            du -sh out
          else
            echo "Output directory 'out' does not exist!"
            echo "Content of current directory:"
            ls -la
            exit 1
          fi

      - name: Prune Large Files
        if: success()
        run: |
          # Remove development files
          find out -name "*.development.js" -type f -delete || true
          find out -name "*.LICENSE.txt" -type f -delete || true
          find out -name "*.map" -type f -delete || true
          
          # Report final size
          echo "Final build size:"
          du -sh out
          echo "Largest files:"
          find out -type f -exec du -h {} \; | sort -rh | head -n 10

      - name: Build And Deploy
        id: builddeploy
        if: success()
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_GLACIER_0599E9010 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "out" 
          api_location: ""
          output_location: ""
          skip_app_build: true

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_GLACIER_0599E9010 }}
          action: "close"
