name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install Dependencies
        run: npm ci

      - name: Create .env.local file
        run: |
          echo "NEXT_TELEMETRY_DISABLED=1" > .env.local
          echo "NEXT_SWC_MINIFY=true" >> .env.local

      - name: Build Next.js Application
        run: npm run build
        
      - name: Debug Build Output
        run: |
          ls -la .next
          echo "Checking if standalone directory exists:"
          ls -la .next/standalone || echo "Standalone directory not found"
          
      - name: Setup Static Files
        run: |
          # Create directories
          mkdir -p .next/standalone/public
          mkdir -p .next/standalone/.next/static
          
          # Copy files
          cp -r public/* .next/standalone/public/ || echo "No files to copy from public directory"
          cp -r .next/static/* .next/standalone/.next/static/ || echo "No static files found"
          
          # Copy server.js
          cp .next/standalone/server.js .next/standalone/index.js || echo "server.js not found"
          
          # Remove cache to reduce size
          rm -rf .next/cache || echo "No cache directory found"
          
          # Show directory structure
          echo "Deployment directory structure:"
          find .next/standalone -type d | sort

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_GLACIER_0599E9010 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: ".next/standalone" 
          api_location: ""
          output_location: ""
          skip_app_build: true

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_GLACIER_0599E9010 }}
          action: "close"
