name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install Production Dependencies
        run: npm ci --omit=dev --no-optional
        
      - name: Install Build Tools
        run: npm install -g terser
        
      - name: Create .env.local file
        run: |
          echo "NEXT_TELEMETRY_DISABLED=1" > .env.local
          echo "NEXT_SWC_MINIFY=true" >> .env.local

      - name: Build Static Site
        run: npm run build

      - name: Check Output Size
        run: |
          echo "Analyzing build output size..."
          du -sh out
          find out -type f -name "*.js" | xargs du -ch | sort -rh | head -10
          find out -type d | xargs du -ch | sort -rh | head -10
          echo "Total number of files:"
          find out -type f | wc -l
          
      - name: Prune Large Files
        run: |
          # Remove any development-only files
          find out -name "*.development.js" -type f -delete
          # Additional size reduction if needed
          find out -name "*.LICENSE.txt" -type f -delete
          
      - name: Create optimized archive
        run: |
          cd out
          tar -czf ../optimized-output.tar.gz .
          cd ..
          echo "Archive size:"
          du -sh optimized-output.tar.gz

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_GLACIER_0599E9010 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "out" 
          api_location: ""
          output_location: ""
          skip_app_build: true

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_GLACIER_0599E9010 }}
          action: "close"
